# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginWIndow(object):

        # Style functions

        stylePopupOk = ("background-color:rgb(100, 156, 83); border-radius: 5px;")
        stylePopupError = ("background-color:rgb(254, 104, 128); border-radius: 5px;")

        styleLineEditOK = ("QLabel{\n"
                "color: rgb(92, 121, 149);\n"
                "}")

        styleLineEditError = ("QLabel{\n"
                "color: rgb(254, 104, 128);\n"
                "}")

        # Functions
        def check_fields(self):
                textUser = ""
                textPw = ""
        
                def show_message(message):
                        self.frame_error_popup.show()
                        self.label_error.setText(message)

                # Check user
                if not self.username.text():
                        textUser = " User empty "
                        self.username_label.setStyleSheet(self.styleLineEditError)
                else:
                        textUser = ""
                        self.username_label.setStyleSheet(self.styleLineEditOK)

                # Check password
                if not self.password.text():
                        textPw = " Password empty "
                        self.password_label.setStyleSheet(self.styleLineEditError)
                else:
                        textPw = ""
                        self.password_label.setStyleSheet(self.styleLineEditOK)

                # Check fields
                if textUser + textPw != '':
                        text = textUser + "| " + textPw
                        show_message(text)
                        self.frame_error_popup.setStyleSheet(self.stylePopupError)
                else:
                        text = " Login successful "
                        if self.save_credentials.isChecked():
                                text = text + " | User credentials have been saved "
                        show_message(text)
                        self.frame_error_popup.setStyleSheet(self.stylePopupOk)

        def setupUi(self, LoginWIndow):
                LoginWIndow.setObjectName("LoginWIndow")
                LoginWIndow.resize(500, 700)
                LoginWIndow.setMinimumSize(QtCore.QSize(500, 700))
                LoginWIndow.setMaximumSize(QtCore.QSize(500, 700))
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/lock_image/images/locksvgicon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                LoginWIndow.setWindowIcon(icon)
                LoginWIndow.setStyleSheet("background-color: rgb(27, 30, 36);")
                self.centralwidget = QtWidgets.QWidget(LoginWIndow)
                self.centralwidget.setObjectName("centralwidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.top = QtWidgets.QFrame(self.centralwidget)
                self.top.setMaximumSize(QtCore.QSize(16777215, 35))
                self.top.setStyleSheet("")
                self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.top.setFrameShadow(QtWidgets.QFrame.Raised)
                self.top.setObjectName("top")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setSpacing(0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.frame_error_popup = QtWidgets.QFrame(self.top)
                self.frame_error_popup.setMaximumSize(QtCore.QSize(550, 16777215))
                self.frame_error_popup.setStyleSheet(self.stylePopupOk)
                self.frame_error_popup.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_error_popup.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_error_popup.setObjectName("frame_error_popup")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error_popup)
                self.horizontalLayout_3.setContentsMargins(45, 0, 10, 0)
                self.horizontalLayout_3.setSpacing(0)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.label_error = QtWidgets.QLabel(self.frame_error_popup)
                self.label_error.setAlignment(QtCore.Qt.AlignCenter)
                self.label_error.setStyleSheet("color: white;")
                self.label_error.setObjectName("label_error")
                self.horizontalLayout_3.addWidget(self.label_error)
                self.close_popup = QtWidgets.QPushButton(self.frame_error_popup)
                self.close_popup.setEnabled(True)
                self.close_popup.setMaximumSize(QtCore.QSize(20, 20))
                self.close_popup.setStyleSheet("QPushButton {\n"
                "    \n"
                "    background-image: url(:/close_image/images/cil-x.png);\n"
                "    background-position: center;\n"
                "}\n"
                "\n"
                "QPushButton:hover {\n"
                "    background-color: rgb(50, 50, 50);\n"
                "    color: rgb(200, 200, 200);\n"
                "}\n"
                "\n"
                "QPushButton::pressed {\n"
                "    background-color: rgb(35, 35, 35);\n"
                "    color: rgb(200, 200, 200);\n"
                "}")
                self.close_popup.setText("")
                self.close_popup.setObjectName("close_popup")
                self.horizontalLayout_3.addWidget(self.close_popup)
                self.horizontalLayout_2.addWidget(self.frame_error_popup)
                self.verticalLayout.addWidget(self.top)
                self.content = QtWidgets.QFrame(self.centralwidget)
                self.content.setStyleSheet("")
                self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.content.setFrameShadow(QtWidgets.QFrame.Raised)
                self.content.setObjectName("content")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setSpacing(0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.login_area = QtWidgets.QFrame(self.content)
                self.login_area.setMaximumSize(QtCore.QSize(450, 550))
                self.login_area.setMouseTracking(True)
                self.login_area.setStyleSheet("")
                self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
                self.login_area.setObjectName("login_area")
                self.lock = QtWidgets.QFrame(self.login_area)
                self.lock.setGeometry(QtCore.QRect(93, 262, 31, 31))
                self.lock.setStyleSheet("background-image: url(:/lock_image/images/locksvg.svg);\n"
                "background-repeat: no-repeat;\n"
                "")
                self.lock.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.lock.setFrameShadow(QtWidgets.QFrame.Raised)
                self.lock.setObjectName("lock")
                self.person = QtWidgets.QFrame(self.login_area)
                self.person.setGeometry(QtCore.QRect(93, 185, 31, 31))
                self.person.setStyleSheet("background-image: url(:/person_image/images/person.svg);\n"
                "background-repeat: no-repeat;")
                self.person.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.person.setFrameShadow(QtWidgets.QFrame.Raised)
                self.person.setObjectName("person")
                self.username = QtWidgets.QLineEdit(self.login_area)
                self.username.setGeometry(QtCore.QRect(133, 170, 191, 41))
                self.username.setMouseTracking(True)
                self.username.setStyleSheet("QLineEdit{\n"
                "\n"
                "    border-radius: 1px;\n"
                "\n"
                "\n"
                "    font-size: 15px;\n"
                "    \n"
                "    color: rgb(100, 100, 100);\n"
                "}\n"
                "\n"
                "QLineEdit::focus{\n"
                "    color: rgb(180, 180, 180);\n"
                "}")
                self.username.setMaxLength(16)
                self.username.setFrame(True)
                self.username.setReadOnly(False)
                self.username.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
                self.username.setClearButtonEnabled(False)
                self.username.setObjectName("username")
                self.login_text_label = QtWidgets.QLabel(self.login_area)
                self.login_text_label.setGeometry(QtCore.QRect(134, 154, 49, 16))
                self.login_text_label.setStyleSheet("color: rgb(130, 130, 130);")
                self.login_text_label.setObjectName("login_text_label")
                self.username_label = QtWidgets.QLabel(self.login_area)
                self.username_label.setGeometry(QtCore.QRect(132, 200, 201, 15))
                
                self.username_label.setStyleSheet(self.styleLineEditOK)
                
                self.username_label.setObjectName("username_label")
                self.password_label = QtWidgets.QLabel(self.login_area)
                self.password_label.setGeometry(QtCore.QRect(131, 279, 201, 15))
                
                self.password_label.setStyleSheet(self.styleLineEditOK)
                
                self.password_label.setObjectName("password_label")
                self.password = QtWidgets.QLineEdit(self.login_area)
                self.password.setGeometry(QtCore.QRect(132, 249, 191, 41))
                self.password.setStyleSheet("QLineEdit{\n"
                "\n"
                "    border-radius: 1px;\n"
                "\n"
                "\n"
                "    font-size: 15px;\n"
                "    \n"
                "    color: rgb(100, 100, 100);\n"
                "}\n"
                "\n"
                "QLineEdit::focus{\n"
                "    color: rgb(180, 180, 180);\n"
                "}")
                self.password.setText("")
                self.password.setMaxLength(16)
                self.password.setEchoMode(QtWidgets.QLineEdit.Password)
                self.password.setObjectName("password")
                self.password_text_label = QtWidgets.QLabel(self.login_area)
                self.password_text_label.setGeometry(QtCore.QRect(133, 233, 61, 16))
                self.password_text_label.setStyleSheet("color: rgb(130, 130, 130);")
                self.password_text_label.setObjectName("password_text_label")
                self.save_credentials = QtWidgets.QCheckBox(self.login_area)
                self.save_credentials.setGeometry(QtCore.QRect(99, 310, 121, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.save_credentials.setFont(font)
                self.save_credentials.setMouseTracking(True)
                self.save_credentials.setStyleSheet("QCheckBox{\n"
                "    color: rgb(200,200,200);\n"
                "}\n"
                "\n"
                "QCheckBox::hover{\n"
                "    color: white;\n"
                "}\n"
                "\n"
                "QCheckBox::indicator{\n"
                "    border: 3px solid rgb(100,100,100);\n"
                "    width: 15px;\n"
                "    height: 15px;\n"
                "    border-radius: 10px;\n"
                "    background-color: rgb(135, 135, 135);\n"
                "}\n"
                "\n"
                "QCheckBox::indicator::hover{\n"
                "    background-color: rgb(151, 151, 151);\n"
                "}\n"
                "\n"
                "QCheckBox::indicator:checked{\n"
                "    border: 3px solid rgb(80,115,79);\n"
                "    background-color: rgb(80, 143, 79);\n"
                "}")
                self.save_credentials.setObjectName("save_credentials")
                self.LoginBtn = QtWidgets.QPushButton(self.login_area)
                self.LoginBtn.setGeometry(QtCore.QRect(93, 353, 261, 41))
                font = QtGui.QFont()
                font.setPointSize(11)
                font.setBold(True)
                self.LoginBtn.setFont(font)
                self.LoginBtn.setStyleSheet("QPushButton{\n"
                "    color: white;\n"
                "    background-color: rgb(55, 61, 74);\n"
                "    border-radius: 5px;\n"
                "}\n"
                "\n"
                "QPushButton::hover{\n"
                "    background-color: rgb(12, 134, 220);\n"
                "    border: white;\n"
                "}\n"
                "\n"
                "QPushButton::pressed{\n"
                "    background-color: rgb(8, 121, 199);\n"
                "    border: white;\n"
                "}")
                self.LoginBtn.setObjectName("LoginBtn")
                self.logo = QtWidgets.QFrame(self.login_area)
                self.logo.setGeometry(QtCore.QRect(46, 20, 301, 90))
                self.logo.setStyleSheet("background-image: url(:/logo/images/logo.png);")
                self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
                self.logo.setObjectName("logo")
                self.horizontalLayout.addWidget(self.login_area)
                self.verticalLayout.addWidget(self.content)
                self.bottom = QtWidgets.QFrame(self.centralwidget)
                self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
                self.bottom.setStyleSheet("background-color: rgb(27, 30, 36);")
                self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
                self.bottom.setObjectName("bottom")
                self.verticalLayout.addWidget(self.bottom)
                LoginWIndow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(LoginWIndow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
                self.menubar.setObjectName("menubar")
                LoginWIndow.setMenuBar(self.menubar)

                # Button functions
                # Close popup function
                self.close_popup.clicked.connect(lambda: self.frame_error_popup.hide())
                        
                # Hide error
                self.frame_error_popup.hide()

                # Login button
                self.LoginBtn.clicked.connect(self.check_fields)

                self.retranslateUi(LoginWIndow)
                QtCore.QMetaObject.connectSlotsByName(LoginWIndow)

        def retranslateUi(self, LoginWIndow):
                _translate = QtCore.QCoreApplication.translate
                LoginWIndow.setWindowTitle(_translate("LoginWIndow", "Login"))
                self.label_error.setText(_translate("LoginWIndow", "ERROR: Username or password not valid"))
                self.username.setPlaceholderText(_translate("LoginWIndow", "Username"))
                self.login_text_label.setText(_translate("LoginWIndow", "Login"))
                self.username_label.setText(_translate("LoginWIndow", "_______________________________________"))
                self.password_label.setText(_translate("LoginWIndow", "_______________________________________"))
                self.password.setPlaceholderText(_translate("LoginWIndow", "Password"))
                self.password_text_label.setText(_translate("LoginWIndow", "Password"))
                self.save_credentials.setText(_translate("LoginWIndow", "Save credentials"))
                self.LoginBtn.setText(_translate("LoginWIndow", "Login"))
                import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWIndow = QtWidgets.QMainWindow()
    ui = Ui_LoginWIndow()
    ui.setupUi(LoginWIndow)
    LoginWIndow.show()
    sys.exit(app.exec_())
